
/* Drop Tables */

DROP TABLE M_USER;
DROP TABLE M_ROLE;
DROP TABLE T_SAMPLE;




/* Create Tables */

CREATE TABLE M_ROLE
(
	ROLE_ID int NOT NULL auto_increment,
	ROLE_NAME varchar(32) NOT NULL,
	ROLE_TYPE varchar(16) NOT NULL,
	SYSTEM_MANAGEMENT boolean DEFAULT 'FALSE' NOT NULL,
	REGISTERED_USERNAME varchar(32) NOT NULL,
	REGISTERED_DATE timestamp NOT NULL,
	UPDATED_USERNAME varchar(32) NOT NULL,
	UPDATED_DATE timestamp NOT NULL,
	DELETED boolean DEFAULT 'FALSE' NOT NULL,
	VERSION int DEFAULT 0 NOT NULL,
	PRIMARY KEY (ROLE_ID)
);


CREATE TABLE M_USER
(
	USER_ID int NOT NULL auto_increment,
	USERNAME varchar(32) NOT NULL,
	PASSWORD varchar(64) NOT NULL,
	DISPLAY_NAME varchar(64) NOT NULL,
	ROLE_ID int NOT NULL,
	EMAIL varchar(256),
	TEL varchar(14),
	REGISTERED_USERNAME varchar(32) NOT NULL,
	REGISTERED_DATE timestamp NOT NULL,
	UPDATED_USERNAME varchar(32) NOT NULL,
	UPDATED_DATE timestamp NOT NULL,
	DELETED boolean DEFAULT 'FALSE' NOT NULL,
	VERSION int DEFAULT 0 NOT NULL,
	PRIMARY KEY (USER_ID)
);


CREATE TABLE T_SAMPLE
(
	SAMPLE_ID int NOT NULL auto_increment,
	SAMPLE_NAME varchar(64) NOT NULL,
	SAMPLE_TYPE varchar(10) NOT NULL,
	SAMPLE_EMAIL varchar(256),
	SAMPLE_PASSWORD varchar(64),
	SAMPLE_CHECKED boolean DEFAULT 'FALSE' NOT NULL,
	SAMPLE_OPTION varchar(16) DEFAULT 'NONE' NOT NULL,
	SAMPLE_REMARK varchar,
	REGISTERED_USERNAME varchar(32) NOT NULL,
	REGISTERED_DATE timestamp NOT NULL,
	UPDATED_USERNAME varchar(32) NOT NULL,
	UPDATED_DATE timestamp NOT NULL,
	DELETED boolean DEFAULT 'FALSE' NOT NULL,
	VERSION int DEFAULT 0 NOT NULL,
	PRIMARY KEY (SAMPLE_ID)
);



/* Create Foreign Keys */

ALTER TABLE M_USER
	ADD FOREIGN KEY (ROLE_ID)
	REFERENCES M_ROLE (ROLE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



