
/* Drop Tables */

DROP TABLE M_USER;
DROP TABLE T_SAMPLE;




/* Create Tables */

CREATE TABLE M_USER
(
	USER_ID int NOT NULL auto_increment,
	USERNAME varchar(32) NOT NULL,
	PASSWORD varchar(60) NOT NULL,
	DISPLAY_NAME varchar(64) NOT NULL,
	REGISTERED_USERNAME varchar(32) NOT NULL,
	REGISTERED_DATE timestamp NOT NULL,
	UPDATED_USERNAME varchar(32) NOT NULL,
	UPDATED_DATE timestamp NOT NULL,
	DELETED boolean DEFAULT 'FALSE' NOT NULL,
	PRIMARY KEY (USER_ID)
);


CREATE TABLE T_SAMPLE
(
	SAMPLE_ID int NOT NULL auto_increment,
	SAMPLE_NAME varchar(64) NOT NULL,
	SAMPLE_TYPE varchar(10) NOT NULL,
	REGISTERED_USERNAME varchar(32) NOT NULL,
	REGISTERED_DATE timestamp NOT NULL,
	UPDATED_USERNAME varchar(32) NOT NULL,
	UPDATED_DATE timestamp NOT NULL,
	DELETED boolean DEFAULT 'FALSE' NOT NULL,
	PRIMARY KEY (SAMPLE_ID)
);



